version: '3'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/HD-E1/rpi/configs/jellyfin:/config
      - /media/HD-E1/rpi/downloads:/downloads
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - /media/HD-E1/rpi/configs/qbittorrent:/config
      - /media/HD-E1/rpi/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    volumes:
      - /media/HD-E1/rpi/configs/cloudflare:/home/nonroot/.cloudflared/
    command: tunnel run raspberry
    restart: unless-stopped
    network_mode: host
